[package]
name = "app"
version = "0.1.0"
edition = "2021"
default-run = "app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
commons ={ path = "../commons"}
